### ISSUE TITLE
Using a branch other than "master" breaks the Spanish translation link on npmjs.com

### ISSUE THREAD

**Issue by binki** [zkat/cacache#103]
https://www.npmjs.com/package/cacache

If I click “español” I get a 404.

**Comment by zkat** [comment]
I think this will be fixed as soon as a new version gets published, since I'm pretty sure the changes needed to marky-markdown to get this to work have already landed

**Comment by zkat** [comment]
Confirmed. It should work now, after I published a new version. Cheers.
