### ISSUE TITLE
Relicense under MIT

### ISSUE THREAD

**Issue by michael-ciniawsky** [zkat/cacache#109]
👋  Hey, has the title already states, would it be possible to consider publishing this project under the MIT License ? We currently have an issue with corporate policy in `uglifyjs-webpack-plugin` ([#120](https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/120)), but it would be awesome if we could continue using `cacache`

**Comment by zkat** [comment]
@michael-ciniawsky would `ISC` be sufficient? That's usually what npm policy licenses things at.

**Comment by michael-ciniawsky** [comment]
¯\_(ツ)_/¯ I don't know for sure tbh :), I just suggested MIT out of the blue as there shouldn't be any issues with that license

**Comment by isaacs** [comment]
Slight +1 for ISC, to match the rest of npm's guts.  @michael-ciniawsky Do you have lawyers or corporate governance/policy folks you can check with?  The ISC license text (if they ask for it) would be this:

```
ISC License

Copyright (c) npm, Inc.

Permission to use, copy, modify, and/or distribute this software for
any purpose with or without fee is hereby granted, provided that the
above copyright notice and this permission notice appear in all copies.

THE SOFTWARE IS PROVIDED "AS IS" AND THE COPYRIGHT HOLDER DISCLAIMS
ALL WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
COPYRIGHT HOLDER BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR
CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS
OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE
OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE
USE OR PERFORMANCE OF THIS SOFTWARE.
```

**Comment by michael-ciniawsky** [comment]
I'm only the middleman here, so I can't 💯  guarantee it, but according to https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/120#issuecomment-338420075 either `ISC` or `MIT` should definitely be sufficient. I will check the JSF (`webpack` && `webpack-contrib`) side again but I assume it is fine aswell. Anyways, thanks in advance for the quick response and openness so far 👍
