### ISSUE TITLE
question - can multiple node processes use the same cache path

### ISSUE THREAD

**Issue by cameronbraid** [zkat/cacache#137]
I see that in the docs you state "immune to to process races"

```
Fault tolerance (immune to corruption, partial writes, process races, etc)
```

Does that mean that multiple node processes can use the same cache path ?

**Comment by zkat** [comment]
Indeed! You don't need any sort of locking mechanism either (and cacache doesn't use one either), so go wild with it. npm uses this feature aggressively so you should be good :)
