### ISSUE TITLE
Version bump for npm/npm#20424 fix

### ISSUE THREAD

**Issue by colinrotherham** [zkat/cacache#138]
Hello @zkat,

Due to https://github.com/npm/npm/issues/20424 (and our use of `npm install *.tar.gz`) we can't move off `npm@5.8` because of the _Error: invalid config key requested: single_ bug we see with tarball installs.

It looks like it was all fixed in https://github.com/zkat/cacache/commit/10d5d9a8c2d42217e12eb16619ba9cc2f5751364 🎉 

Could a new `cacache` please be versioned and make it into `npm@6.3`?

Thanks

**Comment by zkat** [comment]
`npm@6.3.0` is out with the newest cacache. You should be good now. :)
