### ISSUE TITLE
Use better temp filename generation

### ISSUE THREAD

**Issue by zkat** [zkat/cacache#15]
Right now, [`lib/content/put-stream.js`](https://github.com/zkat/cacache/blob/latest/lib/content/put-stream.js) uses [`randomstring`](https://www.npmjs.com/package/randomstring) and some manual munging to create a unique tmp filename.

Use [`unique-filename`](https://www.npmjs.com/package/unique-filename) to generate this instead.

This also means `randomstring` can be dropped as a req, so remove that too.

**Comment by varjmes** [comment]
How about using 'starter' instead of 'easy' as a label? :)

I might play around with this, but I'm not claiming. If I get something useful I'll PR :)
