### ISSUE TITLE
Add contribution documentation

### ISSUE THREAD

**Issue by zkat** [zkat/cacache#20]
https://github.com/zkat/pacote/pull/29 adds LICENSE, CONTRIBUTING.md, and CODE_OF_CONDUCT.md to that project -- cacache should have similar docs added. That is most likely a matter of scanning through the docs and making sure any references to `pacote` are replaced with `cacache`. Eyeballing things to make sure nothing snuck through is also 💯.

**Comment by varjmes** [comment]
#22
