### ISSUE TITLE
Make testDir.reset async

### ISSUE THREAD

**Issue by zkat** [zkat/cacache#34]
Over in pacote, https://github.com/zkat/pacote/pull/13 made `testDir.reset()` operate asynchronously, which should work around random Windows-related failures. Port that over here, since it should play much nicer with the new tap.

**Comment by varjmes** [comment]
I think I'll take a look at this tomorrow!

**Comment by zkat** [comment]
@Charlotteis heads up that I've gotta work on this one over in #36. This is what exposed that awful race I told you about in cacache.

**Comment by varjmes** [comment]
@zkat Ah so you'll do this instead? Np np np.
